### ISSUE TITLE
Why not based on micromatch?

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/matched#4]

**Comment by jonschlinkert** [comment]
sorry just saw this. Obviously I'd love to use micromatch in this, but the matching is only part of it. There are so many edge cases with fs globbing because of windows, and case-sensitive file systems that I decided to stick with node-glob until I have time to do a proper implementation.

**Comment by jonschlinkert** [comment]
Closing, since it has been a while. 

@TrySound how are you? Hope all is well.  on a related topic (to this issue) we're working on [refactoring glob-fs](https://github.com/micromatch/glob-fs/pull/18), please stop by and let us know if you have any thoughts on the API plans before we start working on it.

**Comment by TrySound** [comment]
I'm good. Thank you. Working on css-modules now.
